name: Bug Report
description: "Create a report to help us improve."
title: "[BUG]"
labels: "bug"
assignees: tiann
body:
  - type: markdown
    id: enviroment-info
    attributes:
      value: "## Enviroment Infomation"
  - type: input
    id: device
    validations:
      required: true
    attributes:
      label: "Device name"
      description: "Press your device name(E.G.: Google Pixel 6)"
  - type: input
    id: ksu-version
    validations:
      required: true
    attributes:
      label: "KernelSU version"
      description: "Open KernelSU App,Check out the KernelSU version in the middle.(E.G: 10582)"
  - type: input
    id: app-version
    validations:
      required: true
    attributes:
      label: "KernelSU App version"
      description: "Press and hold the KernelSU app to view the version of the manager in the application version.(E.G: 0.5.7)"
  - type: input
    id: kernel-version
    validations:
      required: true
    attributes:
      label: "Kernel version"
      description: "Open the phone settings, click on the phone option, find the kernel version.(E.G.: 5.10.xxx)"
  - type: input
    id: android-version
    validations:
      required: true
    attributes:
      label: "Android version"
      description: "E.G.: Android12"
  - type: markdown
    id: detail-info
    attributes:
      value: "## Detail Infomation"
  - type: textarea
    id: what-happened
    attributes:
      label: "Description of the problem."
      description: "Briefly describe the problem you are experiencing,Describe the bug A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: how-happened
    attributes:
      label: "Steps to reproduce"
      description: "If the action can reproduce the problem."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected correct result"
  - type: textarea
    id: logs
    attributes:
      label: "Related log output"
      render: shell
  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: "If you have other information to provide, you can fill it in here (you can provide screenshots, videos, etc.)."
