name: build deb

on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

jobs:

  build-deb:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup environment

        run: |

          sudo apt update

          sudo apt install -y debhelper build-essential clang dpkg-dev libcap-dev pkg-config 

      - name: Pull source code

        run: |

          git clone https://github.com/dabao1955/moe-container-manager/ code
          
      - name: Build deb

        run: |

          cd code && sudo dpkg-buildpackage -b -us -uc && cp ../*.deb ./
      - name: Upload builded to artifact

        uses: actions/upload-artifact@v3

        with:

          name: moe-container-manager_0.0.1alpha_amd64.deb

          path: moe-container-manager_0.0.1alpha_amd64.deb
