name: build deb

on:

  push:

    branches: [ "main" ]

  pull_request:

jobs:

  build-deb:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo

        uses: actions/checkout@v4

      - name: Setup environment

        run: |

          sudo apt update

          sudo apt install -y debhelper build-essential clang dpkg-dev libcap-dev pkg-config libseccomp-dev golang

          
      - name: Build deb

        run: |

          sudo dpkg-buildpackage -b -us -uc && cp ../*.deb ./
      - name: Upload builded to artifact

        uses: actions/upload-artifact@v3

        with:

          name: moe-container-manager_0.0.1beta_amd64.deb.zip

          path: moe-container-manager_0.0.1beta_amd64.deb
