name: CI

on:

  push:

    branches: [ "main" ]

  pull_request:

jobs:

  build-deb-amd64:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo

        uses: actions/checkout@v4

      - name: Setup environment

        run: |

          sudo apt update

          sudo apt install -y debhelper build-essential clang dpkg-dev libcap-dev pkg-config libseccomp-dev golang lld

          
      - name: Build deb

        run: |

          sudo dpkg-buildpackage -b -us -uc && cp ../*.deb ./
      - name: Upload builded to artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3

        with:

          name: moe-container-manager_0.0.1rc0_amd64.deb.zip

          path: moe-container-manager_0.0.1rc0_amd64.deb



  build-deb-arm64:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo

        uses: actions/checkout@v4

      - name: Build pkg ARM64 
        uses: pguyot/arm-runner-action@v2 
        with: 
           base_image: raspios_lite_arm64:latest 
           bind_mount_repository: true 
           commands: | 
             sudo apt update

             sudo apt install -y debhelper build-essential clang dpkg-dev libcap-dev pkg-config libseccomp-dev golang lld

             sudo dpkg-buildpackage -b -us -uc && cp ../*.deb ./
      - name: Upload builded to artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3

        with:

          name: moe-container-manager_0.0.1rc0_arm64.deb.zip

          path: moe-container-manager_0.0.1rc0_arm64.deb
