name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-deb-amd64:
    container: debian:bookworm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          apt update
          apt install -y debhelper build-essential clang dpkg-dev libcap-dev pkg-config git libseccomp-dev golang lld cmake libpthreadpool0 libpthreadpool-dev shfmt perl libspdlog-dev

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build deb
        run: |
          dpkg-buildpackage -b -us -uc && cp ../moe-container-manager_* ./out -rv && chmod 755 -R out/*
      - name: Upload builded to artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4

        with:
          name: moe-container-manager_0.0.1rc0_amd64.deb.zip
          path: out/moe*
