name: CI

on:

  push:

    branches: [ "main" ]

  pull_request:
  workflow_dispatch:

jobs:

  build-deb-amd64:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo

        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup environment

        run: |

          sudo apt update

          sudo apt install -y debhelper build-essential clang dpkg-dev libcap-dev pkg-config libseccomp-dev golang lld cmake libpthreadpool0 libpthreadpool-dev

      - name: Build deb
        run: |
          sudo dpkg-buildpackage -b -us -uc &&sudo cp ../moe-container-manager_* ./out -rv && sudo chmod 755 -R -v out/*
      - name: Upload builded to artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3

        with:

          name: moe-container-manager_0.0.1rc0_amd64.deb.zip

          path: out/*
