name: doc

on:

  push:

    branches: [ "main" ]

  pull_request:

jobs:

  build-doc:

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout repo

        uses: actions/checkout@v4

      - name: Setup environment

        run: |

          sudo apt update

          sudo apt install -y python3 python3-pip

          cd doc 

          pip install -r requirements.txt

      - name: Build html
        run: cd doc && make html

      - name: Upload html
        uses: actions/upload-artifact@v3
        with:
          name: doc
          path: doc/*
